### ISSUE TITLE
[DASHBOARD] Feat: Create Home page

### ISSUE THREAD

**Issue by RangoDisco** [RangoDisco/zelvy#3]
## Goal
Allow user to have better insights on the current goals, previous days and progress with charts and all.

## Features
- Daily goal status
- Being able to open a calendar and see any previous day
- Graphs comparing goals between different time period (compared to last week, last month etc...)
- Workout history

## Tech
Right now prolly leaning towards [Svelte/kit](https://kit.svelte.dev/) & something like [daisyui](https://daisyui.com/) or even just raw [tailwind](https://tailwindcss.com/)

#### Basic mobile mock up
![Image](https://github.com/user-attachments/assets/e917f39c-9296-4728-ae4b-e78572103534)

#### Basic desktop wireframe
![Image](https://github.com/user-attachments/assets/6f617402-c4b6-4703-b127-a453da90f72c)

**Comment by Pefouk** [comment]
Ok 👍
